INSERT INTO coefficient (niveau_etude, specialite, matiere, coefficient) VALUES
('Seconde', 'A4', 'Allemand', 2),
('Seconde', 'A4', 'Anglais', 3),
('Seconde', 'A4', 'Français', 4),
('Seconde', 'A4', 'Espagnol', 2),
('Seconde', 'A4', 'ECM', 1),
('Seconde', 'A4', 'Histoire-Géo', 3),
('Seconde', 'A4', 'Mathématiques', 5),
('Seconde', 'A4', 'Physique-Chimie', 4),
('Seconde', 'A4', 'SVT', 3),
('Seconde', 'A4', 'EPS', 2),
('Seconde', 'A4', 'Musique', 1),

('Première', 'D', 'Allemand', 2),
('Première', 'D', 'Anglais', 3),
('Première', 'D', 'Français', 4),
('Première', 'D', 'Espagnol', 2),
('Première', 'D', 'ECM', 1),
('Première', 'D', 'Histoire-Géo', 3),
('Première', 'D', 'Mathématiques', 5),
('Première', 'D', 'Physique-Chimie', 4),
('Première', 'D', 'SVT', 3),
('Première', 'D', 'EPS', 2),
('Première', 'D', 'Musique', 1);
